project:
  type: website

website:
  title: "Dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true
  dashboard:
    css: styles.css
    # This is the key that fixes the problem for dashboards
    echo: false



