project:
  type: website

website:
  title: "Dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

# All format-specific options go under this single 'format' key
format:
  # Defaults for regular HTML pages
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true